services:
  - type: web
    name: Spisok-bot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-cq6i3ijv2p9s73cn43tg-a:5432/spisokbot
      - key: TELEGRAM_BOT_TOKEN
        value: 7326836857:AAEzfT-cPEddK8J-QKQTpXbuuGhQR_rtiVo
